module.exports = {
    APPOINTMENT_TYPE_NEW: 'New',
    APPOINTMENT_TYPE_FOLLOW_UP: 'Follow Up',
    MAX_APPOINTMENT_COUNT : 3,
    DATETIME_FORMAT: 'MM-DD-YYYY HH:MM',
    MINUTE_INCREMENTS: [0, 15, 30, 45]
};